#!/usr/bin/env python3
"""Batch-caption an image directory with a trained RADIO1D -> RWKV checkpoint.

The wanted set is defined by an existing one-caption-per-image reference
directory. Outputs use the same basenames, making side-by-side review trivial.
Completed nonempty outputs are resumable and are never regenerated by default.
"""
from __future__ import annotations

import argparse
import json
import sys
import tempfile
import time
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rwkv_lab.deep_vision import LayerMatchedVisionInjector
from rwkv_lab.engram_lmb import LexicalMemoryBank, attach_engram, float_growth_params
from rwkv_lab.generate import WorldVocab
from rwkv_lab.moonvit import checkpoint_fingerprint, valid_torch_archive_storages
from rwkv_lab.radio1d_rwkv import (
    RadioFeatureProjector,
    RadioPrefixInjector,
    load_radio1d_h,
)
from rwkv_lab.rwkv_finetune import load_g1g_fla
from rwkv_lab.vision_caption import checkpoint_runtime_scales
from rwkv_lab.vision_loop import (
    install_factored_timemix,
    load_loop_adapter_state,
    set_loop_enabled,
    set_loop_scale,
)
from rwkv_lab.vision_train import write_eval_samples


IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}


def load_runtime(checkpoint: Path):
    blob = torch.load(checkpoint, map_location="cpu", weights_only=False)
    if not valid_torch_archive_storages(checkpoint, blob):
        raise RuntimeError(f"checkpoint archive integrity check failed: {checkpoint}")
    if int(blob.get("schema", -1)) != 3:
        raise RuntimeError(f"unsupported vision checkpoint schema {blob.get('schema')}")
    args = blob["args"]
    if args.get("vision_backend") != "radio1d":
        raise RuntimeError("this command requires a RADIO1D checkpoint")
    for name in ("rwkv", "radio_model"):
        expected = args.get("rwkv_fingerprint" if name == "rwkv" else "radio_fingerprint")
        if expected and checkpoint_fingerprint(args[name]) != expected:
            raise RuntimeError(f"{name} weights no longer match the caption checkpoint")

    step = int(blob["step"])
    loop_enabled, loop_scale, engram_scale = checkpoint_runtime_scales(args, step)

    print({"phase": "load_rwkv", "path": args["rwkv"]}, flush=True)
    rwkv = load_g1g_fla(args["rwkv"], device="cuda")
    rwkv.requires_grad_(False)

    engram = None
    if bool(args.get("engram", False)):
        sites = sorted({
            int(value.strip())
            for value in str(args.get("engram_sites", "3,15")).split(",")
            if value.strip()
        })
        vocab_size = int(rwkv.config.vocab_size)
        engram = LexicalMemoryBank(
            hidden_size=int(rwkv.config.hidden_size),
            vocab_size=vocab_size,
            layer_sites=sites,
            d_row=int(args.get("engram_drow", 128)),
            table_rows=min(int(args.get("engram_rows", vocab_size)), vocab_size),
            num_heads=int(rwkv.config.num_heads),
            max_loops=int(args["loop_count"]),
            boundary_id=args.get("engram_boundary_id", 0),
        ).to(device="cuda", dtype=torch.bfloat16)
        float_growth_params(engram)
        attach_engram(rwkv, engram, resolve="model.layers")
        rwkv.engram = engram
        engram.load_state_dict(blob["engram"])
        engram.set_warmup(engram_scale)
        engram.eval()

    wrappers = install_factored_timemix(
        rwkv,
        n_loops=int(args["loop_count"]),
        gate_cap=float(args["loop_gate_cap"]),
        loop_index=bool(args["loop_index"]),
    )
    load_loop_adapter_state(wrappers, blob["loops"])
    set_loop_enabled(wrappers, loop_enabled)
    set_loop_scale(wrappers, loop_scale)

    projector = RadioFeatureProjector(
        adaptive_complexity=bool(args.get("radio_adaptive_complexity", False)),
        complexity_budget_ratio=float(args.get("radio_complexity_budget_ratio", 0.75)),
        complexity_token_quantum=int(args.get("radio_complexity_token_quantum", 16)),
    ).cuda().float()
    projector.load_state_dict(blob["projector"])
    projector.eval()

    deep_vision = None
    deep_sites = sorted({
        int(value.strip())
        for value in str(args.get("deep_vision_layers", "")).split(",")
        if value.strip()
    })
    if deep_sites:
        deep_vision = RadioPrefixInjector(
            int(rwkv.config.hidden_size), deep_sites,
            rank=int(args.get("deep_vision_rank", 256)),
            token_quantum=(int(args.get("radio_complexity_token_quantum", 16))
                           if args.get("radio_adaptive_complexity", False) else 128),
        ).cuda().float()
        deep_vision.install(rwkv.model.layers)
        deep_vision.load_state_dict(blob["deep_vision"])
        deep_vision.eval()

    layer_vision = None
    layer_sites = sorted({
        int(value.strip())
        for value in str(args.get("layer_vision_layers", "")).split(",")
        if value.strip()
    })
    if layer_sites:
        layer_vision = LayerMatchedVisionInjector(
            int(rwkv.config.hidden_size), layer_sites,
            rank=int(args.get("layer_vision_rank", 256)),
        ).cuda().float()
        layer_vision.install(rwkv.model.layers)
        layer_vision.load_state_dict(blob["layer_vision"])
        layer_vision.eval()

    rwkv.eval()
    print({"phase": "load_radio1d", "path": args["radio_model"]}, flush=True)
    vision = load_radio1d_h(args["radio_model"])
    vision.radio_revision = args["radio_revision"]
    vision.radio_max_detail_tiles = int(args["radio_max_detail_tiles"])
    vision.radio_tile_batch = int(args["radio_tile_batch"])
    vision.radio_adaptive_token_threshold = int(args["radio_adaptive_token_threshold"])
    return blob, args, rwkv, projector, vision, engram, deep_vision, layer_vision, wrappers


def source_images(image_dir: Path) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for path in image_dir.iterdir():
        if not path.is_file() or path.suffix.casefold() not in IMAGE_SUFFIXES:
            continue
        if path.stem in result:
            raise RuntimeError(
                f"ambiguous image stem {path.stem!r}: {result[path.stem]} and {path}")
        result[path.stem] = path
    return result


def atomic_text(path: Path, value: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(value.rstrip() + "\n", encoding="utf-8")
    temporary.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--images", type=Path, required=True)
    parser.add_argument("--reference-captions", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--feature-cache", type=Path, required=True)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--max-new", type=int, default=768)
    parser.add_argument("--overwrite", action="store_true")
    cli = parser.parse_args()
    if cli.batch < 1 or cli.max_new < 1:
        raise SystemExit("--batch and --max-new must be positive")

    references = sorted(cli.reference_captions.glob("*.txt"))
    available = source_images(cli.images)
    missing = [path.stem for path in references if path.stem not in available]
    if missing:
        raise SystemExit(f"missing {len(missing)} source images: {missing}")
    cli.output.mkdir(parents=True, exist_ok=True)
    cli.feature_cache.mkdir(parents=True, exist_ok=True)
    pending = [path for path in references if cli.overwrite or not (
        (cli.output / path.name).is_file()
        and (cli.output / path.name).stat().st_size > 1)]
    print({"phase": "plan", "references": len(references),
           "pending": len(pending), "output": str(cli.output)}, flush=True)
    if not pending:
        return

    started = time.perf_counter()
    (blob, args, rwkv, projector, vision, engram, deep_vision,
     layer_vision, wrappers) = load_runtime(cli.checkpoint)
    load_seconds = time.perf_counter() - started
    vocab = WorldVocab()
    torch.cuda.reset_peak_memory_stats()

    completed = 0
    with tempfile.TemporaryDirectory(prefix="rwkv-captions-") as temporary:
        work = Path(temporary)
        for offset in range(0, len(pending), cli.batch):
            batch_refs = pending[offset:offset + cli.batch]
            rows = [{
                "image": available[reference.stem].resolve(),
                "text": reference.read_text(encoding="utf-8").strip() or "reference unavailable",
                "prompt": str(args["prompt"]),
                "source": "dolly_gemini_comparison",
            } for reference in batch_refs]
            batch_out = work / f"batch_{offset:05d}"
            batch_started = time.perf_counter()
            artifact = write_eval_samples(
                rows, list(range(len(rows))), step=int(blob["step"]), ppl=0.0,
                rwkv=rwkv, projector=projector, vision=vision, engram=engram,
                cache_dir=cli.feature_cache, vocab=vocab, prompt=str(args["prompt"]),
                out=batch_out, count=len(rows), max_new=cli.max_new,
                deep_vision=deep_vision, layer_vision=layer_vision,
                sandwich_prompt=bool(args.get("sandwich_prompt", False)),
                sandwich_lead_prompt=str(args.get("sandwich_lead_prompt", "")),
                wrappers=wrappers,
            )
            if artifact is None:
                raise RuntimeError("caption generation produced no artifact")
            result = json.loads(artifact.read_text(encoding="utf-8"))
            by_stem = {Path(item["image"]).stem: item for item in result["items"]}
            for reference in batch_refs:
                item = by_stem.get(reference.stem)
                if item is None:
                    raise RuntimeError(f"caption result omitted {reference.stem}")
                atomic_text(cli.output / reference.name, str(item["caption"]))
                completed += 1
            print({
                "phase": "batch", "completed": completed, "total": len(pending),
                "seconds": round(time.perf_counter() - batch_started, 3),
                "peak_allocated_gib": round(torch.cuda.max_memory_allocated() / 2**30, 2),
                "peak_reserved_gib": round(torch.cuda.max_memory_reserved() / 2**30, 2),
            }, flush=True)

    print({
        "phase": "complete", "captions": completed,
        "load_seconds": round(load_seconds, 3),
        "total_seconds": round(time.perf_counter() - started, 3),
        "output": str(cli.output),
    }, flush=True)


if __name__ == "__main__":
    main()
