#!/usr/bin/env bash
#
# Regenerate every committed protobuf binding from the .proto sources, or, with
# --check, fail when what is committed no longer matches what the proto says.
#
# There are four generated files and they are committed to the tree:
#
#   dashboard/gen/trainvm/v1/trainvm.pb.go
#   dashboard/gen/trainvm/v1/trainvm_grpc.pb.go
#   src/trainvm/v1/trainvm_pb2.py
#   src/trainvm/v1/trainvm_pb2_grpc.py
#
# Until this script covered all four, only the Python pair had a generator and
# nothing compared either pair against the proto. They drifted, in the quietest
# way available: `GetReconciliationStatus` was added to the service and neither
# grpc stub was regenerated, so the Go client had no method and the Python
# servicer had no handler, with CI green. That is not a build error in either
# language -- a message change nobody reads produces no symptom at all, and a
# service change produces a missing method that only bites whoever calls it
# next, possibly months later and possibly from the other language. So a gate
# that merely compiles the stubs would not have caught it; the regenerated
# bytes have to be compared against the committed ones, which is what --check
# does.
#
# Generator versions are pinned below because each one stamps its own version
# into the header of the file it emits. An unpinned generator therefore reports
# a version bump as a diff indistinguishable from real drift, and a gate that
# cries drift on every runner upgrade gets switched off. Change a pin only in
# the same commit as the bindings it regenerates.
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repository_root}"

# Pinned generators. The three Go-side values are the ones recorded in the
# headers of dashboard/gen/**; protoc stamps itself as "v7.35.1" there, which is
# protobuf's internal numbering for the release tagged v35.1 and reported by
# `protoc --version` as "libprotoc 35.1". All three spellings mean one release.
#
# grpcio-tools carries its own bundled protoc and is deliberately held below
# protobuf 7: the optional SM120 CUTLASS stack requires protobuf <7. That is why
# the Python pair is generated by a different protoc than the Go pair, and why
# the two pins move independently.
readonly protoc_version="35.1"
readonly protoc_release_sha256="6930ebf62bd4ea607b98fff052596c6ee564b9835b4ce172c75a3f53ae9d91b7"
readonly protoc_gen_go_version="v1.36.11"
readonly protoc_gen_go_grpc_version="v1.6.2"
readonly grpcio_tools_version="1.76.0"

check_only=0
case "${1-}" in
  --check) check_only=1 ;;
  "") ;;
  *)
    echo "usage: ${BASH_SOURCE[0]} [--check]" >&2
    exit 2
    ;;
esac

tool_cache="${XDG_CACHE_HOME:-${HOME}/.cache}/trainvm-proto-generators"
mkdir -p "${tool_cache}"

# Runtime code generation is forbidden, so these tools exist only to produce the
# committed bindings. They are fetched into a cache outside the worktree rather
# than vendored, and every one of them is version-checked after install: a tool
# that silently answered with a different version would produce exactly the
# false drift this gate must not produce.
#
# These report through globals rather than by echoing a path into a command
# substitution, and that is not a style preference. `errexit` does not abort the
# caller when a command inside `$( )` fails, so written the other way both the
# release checksum and both version assertions passed a deliberately corrupted
# pin: the download was tampered with, `sha256sum` reported the mismatch, and
# the script carried on and printed PASSED. An unverified guard inside a gate is
# the same defect this gate exists to catch, one level up.
protoc_binary=""
ensure_protoc() {
  local pinned="libprotoc ${protoc_version}"
  if command -v protoc >/dev/null 2>&1 && [[ "$(protoc --version)" == "${pinned}" ]]; then
    protoc_binary="$(command -v protoc)"
    return
  fi
  local directory="${tool_cache}/protoc-${protoc_version}"
  local binary="${directory}/bin/protoc"
  if [[ ! -x "${binary}" ]]; then
    local url="https://github.com/protocolbuffers/protobuf/releases/download/v${protoc_version}/protoc-${protoc_version}-linux-x86_64.zip"
    local archive="${directory}.zip"
    echo "fetching protoc ${protoc_version}" >&2
    curl --fail --silent --show-error --location --output "${archive}" "${url}"
    if ! printf '%s  %s\n' "${protoc_release_sha256}" "${archive}" |
        sha256sum --check --status; then
      rm -f "${archive}"
      echo "protoc ${protoc_version} download does not match its pinned sha256" >&2
      exit 1
    fi
    rm -rf "${directory}"
    unzip -q "${archive}" -d "${directory}"
    rm -f "${archive}"
  fi
  if [[ "$("${binary}" --version)" != "${pinned}" ]]; then
    echo "cached protoc is not ${pinned}" >&2
    exit 1
  fi
  protoc_binary="${binary}"
}

go_plugin_binary=""
ensure_go_plugin() {
  local name="$1" module="$2" version="$3"
  local directory="${tool_cache}/${name}-${version}"
  local binary="${directory}/${name}"
  if [[ ! -x "${binary}" ]]; then
    echo "installing ${name} ${version}" >&2
    GOBIN="${directory}" go install "${module}@${version}"
  fi
  # protoc-gen-go reports "protoc-gen-go v1.36.11"; protoc-gen-go-grpc reports
  # "protoc-gen-go-grpc 1.6.2", without the v. Match on the bare number.
  local reported
  reported="$("${binary}" --version)"
  if [[ "${reported}" != *"${version#v}"* ]]; then
    echo "${binary} reports '${reported}', expected ${version}" >&2
    exit 1
  fi
  go_plugin_binary="${binary}"
}

staging="$(mktemp -d)"
trap 'rm -rf "${staging}"' EXIT
mkdir -p "${staging}/python" "${staging}/go"

# Every .proto under proto/, not a hardcoded list: adding a second protocol file
# should not be a silent no-op in the one script that keeps bindings honest.
mapfile -t proto_sources < <(find proto -name '*.proto' -type f | sort)
(( ${#proto_sources[@]} > 0 )) || { echo "no .proto sources under proto/" >&2; exit 1; }

uvx --from "grpcio-tools==${grpcio_tools_version}" \
  python -m grpc_tools.protoc \
  --proto_path=proto \
  --python_out="${staging}/python" \
  --grpc_python_out="${staging}/python" \
  "${proto_sources[@]}"

ensure_protoc
protoc="${protoc_binary}"
ensure_go_plugin protoc-gen-go \
  google.golang.org/protobuf/cmd/protoc-gen-go "${protoc_gen_go_version}"
go_plugin="${go_plugin_binary}"
ensure_go_plugin protoc-gen-go-grpc \
  google.golang.org/grpc/cmd/protoc-gen-go-grpc "${protoc_gen_go_grpc_version}"
go_grpc_plugin="${go_plugin_binary}"

# --go_opt=module strips the go_package prefix ("trainboard/gen") from the
# emitted path, so the output lands at <out>/trainvm/v1/ rather than
# <out>/trainboard/gen/trainvm/v1/.
"${protoc}" \
  --plugin="protoc-gen-go=${go_plugin}" \
  --plugin="protoc-gen-go-grpc=${go_grpc_plugin}" \
  --proto_path=proto \
  --go_out="${staging}/go" --go_opt=module=trainboard/gen \
  --go-grpc_out="${staging}/go" --go-grpc_opt=module=trainboard/gen \
  "${proto_sources[@]}"

declare -A destination_of=()
collect() {
  local staged_root="$1" destination_root="$2" file
  while IFS= read -r file; do
    destination_of["${file}"]="${destination_root}/${file#"${staged_root}"/}"
  done < <(find "${staged_root}" -type f | sort)
}
collect "${staging}/python" src
collect "${staging}/go" dashboard/gen

problems=()
for staged in "${!destination_of[@]}"; do
  destination="${destination_of[${staged}]}"
  if (( check_only )); then
    if [[ ! -f "${destination}" ]]; then
      problems+=("${destination} (generated but not committed)")
    elif ! cmp --silent "${staged}" "${destination}"; then
      problems+=("${destination} (committed bytes differ from the proto)")
      diff -u "${destination}" "${staged}" | head -40 >&2 || true
    fi
  else
    mkdir -p "$(dirname "${destination}")"
    cp "${staged}" "${destination}"
  fi
done

# A binding left behind for a proto that no longer exists is drift too, and it
# is invisible to the loop above because nothing regenerates it.
committed_bindings() {
  find src dashboard/gen \
    \( -name '*_pb2.py' -o -name '*_pb2_grpc.py' -o -name '*.pb.go' \) \
    -type f 2>/dev/null | sort
}
while IFS= read -r committed; do
  [[ -n "${committed}" ]] || continue
  found=0
  for destination in "${destination_of[@]}"; do
    [[ "${destination}" == "${committed}" ]] && { found=1; break; }
  done
  (( found )) || problems+=("${committed} (committed but no proto generates it)")
done < <(committed_bindings)

count="${#destination_of[@]}"
if (( ${#problems[@]} > 0 )); then
  for problem in "${problems[@]}"; do
    echo "DRIFTED: ${problem}"
  done
  echo "trainvm proto bindings: FAILED — ${#problems[@]} of ${count} bindings" \
       "disagree with ${proto_sources[*]}; run scripts/generate_trainvm_proto.sh"
  exit 1
fi

if (( check_only )); then
  echo "trainvm proto bindings: PASSED — ${count} bindings match ${proto_sources[*]}"
else
  echo "trainvm proto bindings: PASSED — regenerated ${count} bindings from ${proto_sources[*]}"
fi
