# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trainvm.v1 import trainvm_pb2 as trainvm_dot_v1_dot_trainvm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trainvm/v1/trainvm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainVMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitExperiment = channel.unary_unary(
                '/trainvm.v1.TrainVM/SubmitExperiment',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentResponse.FromString,
                _registered_method=True)
        self.DiffPlan = channel.unary_unary(
                '/trainvm.v1.TrainVM/DiffPlan',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.PlanDiffRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.PlanDiffResponse.FromString,
                _registered_method=True)
        self.CommandRun = channel.unary_unary(
                '/trainvm.v1.TrainVM/CommandRun',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.RunCommandResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/trainvm.v1.TrainVM/GetRun',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetRunRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.RunSummary.FromString,
                _registered_method=True)
        self.GetCompiledPlan = channel.unary_unary(
                '/trainvm.v1.TrainVM/GetCompiledPlan',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/trainvm.v1.TrainVM/ListRuns',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/trainvm.v1.TrainVM/WatchEvents',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.EventEnvelope.FromString,
                _registered_method=True)
        self.GetControlView = channel.unary_unary(
                '/trainvm.v1.TrainVM/GetControlView',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetControlViewRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetControlViewResponse.FromString,
                _registered_method=True)
        self.GetDescriptor = channel.unary_unary(
                '/trainvm.v1.TrainVM/GetDescriptor',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.DescriptorRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.DescriptorResponse.FromString,
                _registered_method=True)
        self.GetHostAuthorityStatus = channel.unary_unary(
                '/trainvm.v1.TrainVM/GetHostAuthorityStatus',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusRequest.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusResponse.FromString,
                _registered_method=True)


class TrainVMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompiledPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescriptor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostAuthorityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainVMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitExperiment,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentResponse.SerializeToString,
            ),
            'DiffPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffPlan,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.PlanDiffRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.PlanDiffResponse.SerializeToString,
            ),
            'CommandRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandRun,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.RunCommandRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.RunCommandResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetRunRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.RunSummary.SerializeToString,
            ),
            'GetCompiledPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompiledPlan,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.ListRunsRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.ListRunsResponse.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.WatchEventsRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.EventEnvelope.SerializeToString,
            ),
            'GetControlView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlView,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetControlViewRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetControlViewResponse.SerializeToString,
            ),
            'GetDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescriptor,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.DescriptorRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.DescriptorResponse.SerializeToString,
            ),
            'GetHostAuthorityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostAuthorityStatus,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusRequest.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainvm.v1.TrainVM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainvm.v1.TrainVM', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainVM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/SubmitExperiment',
            trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.SubmitExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiffPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/DiffPlan',
            trainvm_dot_v1_dot_trainvm__pb2.PlanDiffRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.PlanDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/CommandRun',
            trainvm_dot_v1_dot_trainvm__pb2.RunCommandRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/GetRun',
            trainvm_dot_v1_dot_trainvm__pb2.GetRunRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.RunSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompiledPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/GetCompiledPlan',
            trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.GetCompiledPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/ListRuns',
            trainvm_dot_v1_dot_trainvm__pb2.ListRunsRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trainvm.v1.TrainVM/WatchEvents',
            trainvm_dot_v1_dot_trainvm__pb2.WatchEventsRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.EventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/GetControlView',
            trainvm_dot_v1_dot_trainvm__pb2.GetControlViewRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.GetControlViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/GetDescriptor',
            trainvm_dot_v1_dot_trainvm__pb2.DescriptorRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.DescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostAuthorityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainvm.v1.TrainVM/GetHostAuthorityStatus',
            trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusRequest.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.GetHostAuthorityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/trainvm.v1.WorkerControl/Connect',
                request_serializer=trainvm_dot_v1_dot_trainvm__pb2.WorkerToController.SerializeToString,
                response_deserializer=trainvm_dot_v1_dot_trainvm__pb2.ControllerToWorker.FromString,
                _registered_method=True)


class WorkerControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=trainvm_dot_v1_dot_trainvm__pb2.WorkerToController.FromString,
                    response_serializer=trainvm_dot_v1_dot_trainvm__pb2.ControllerToWorker.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainvm.v1.WorkerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainvm.v1.WorkerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/trainvm.v1.WorkerControl/Connect',
            trainvm_dot_v1_dot_trainvm__pb2.WorkerToController.SerializeToString,
            trainvm_dot_v1_dot_trainvm__pb2.ControllerToWorker.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
